# -*- coding: utf-8 -*-
"""(01)MyFirstJupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n3NcnXG0a2FENQH6xCz1CRGuZR337ov9
"""

1+1 #google's computer is actually computing this and my computer is showing the result.

i=5 #variable or container
i

i*7

i=6

i

i*7

type(i) #data type

f=5.0
type(f)

f*8

f=5.2
f*f

f**3

i=2
i**3 # power 3

s="hello" #can also use single quotes
type(s)

s="5"
type(s) #not int

i=2
i/2
type(i/2)

s="3"
s*10
#s/10 #error:cant divide string by int and we cant subtract strings

s1="My name is "
s2="Resh"
s1+s2

s1[3] #accessing char in string

b=True #boolean
type(b)

mylist = [1, 6.2, 8, -10, 63] #square brackets -list
#list - cllection
mylist[3] #gives -10, indexing starts from 0

mytuple = (1, 6.2, 8, -10, 63) #round brackets
mytuple

mytuple[0]

mylist[3]=14
mylist #we can change the elements inside the tuple

# mytuple[3]=1
# mytuple #we cant change the elements inside the tuple

mydict={'name':'resh',
        'course':'msds',
        'university': ['university of', 'delaware', 'newark','usa'],
        'sem':3,
        'smoker':False} #curly brackets, have pairs (key:value)

mydict

mydict['university'] #this gives the output as list

mydict['university'][1]

mydict['name']

# f=16.0
# sqrt(f)#there is no sqrt() func.
#there is sqrt() func in numpy
# so we have to import numpy module

import numpy as np
np.sqrt(f)

from numpy import *
sqrt(f)

import math as ma
sqrt(f)

# we should'nt import everything from the module
# because there might be same name functions but different functionalities in both modules.

i=6
i>5

i<6

z=6

z==6

z!=6

mylist

for val in mylist:
  print(val)

for val in mylist:
  if val==8:
    print(val)
  else:
    print("nah")

